USE master
GO

DROP DATABASE dbJPA
GO

-- Validando la existencia de la base de datos dbJPA
IF db_id('dbJPA') IS NOT NULL
    PRINT '*** Si existe la base de datos ***'
ELSE
    PRINT '--- No existe la base de datos, procederé a crearla ---'
    CREATE DATABASE dbJPA
GO

-- Poner en uso la base de datos
USE dbJPA
GO

-- Creación de las tablas
CREATE TABLE ALBUM(
    CODALB      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMALB      VARCHAR(100) NOT NULL,
    IMGALB      VARCHAR(100) NOT NULL,
    DESCALB     TEXT NOT NULL,
    ANIALB      INTEGER NOT NULL,
    FORMALB     VARCHAR(10) NOT NULL,
    VALALB      DECIMAL(6,2) NOT NULL,
    RATALB      INTEGER NOT NULL,
    FECCREALB   DATETIME NOT NULL,
    FECMODALB   DATETIME NOT NULL,
    ESTALB      INTEGER NOT NULL,
    CODDIS      INTEGER NOT NULL,
    CODART      INTEGER NOT NULL
)

CREATE TABLE ARTISTA(
    CODART      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMART      VARCHAR(100) NOT NULL,
    IMGART      VARCHAR(100) NOT NULL,
    FECCREART   DATETIME NOT NULL,
    FECMODART   DATETIME NOT NULL,
    ESTART      INTEGER NOT NULL,
    CODNAC      INTEGER NOT NULL,
    CODSUBGEN   INTEGER NOT NULL
)

CREATE TABLE CARRITO(
    CODCAR      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    CODPER      INTEGER NOT NULL
)

CREATE TABLE CARRITOALBUM(
    CODCARALB       INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    CANTCARALB      INTEGER NOT NULL,
    FECCOMCARALB    DATETIME NOT NULL,
    ESTCARALB       VARCHAR(45),
    CODCAR          INTEGER NOT NULL,
    CODALB          INTEGER NOT NULL,
    CODFAC          INTEGER NOT NULL
)

CREATE TABLE DISQUERA(
    CODDIS      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DESDIS      VARCHAR(100) NOT NULL,
    FECCREDIS   DATETIME NOT NULL,
    FECMODDIS   DATETIME NOT NULL,
    ESTDIS      INTEGER NOT NULL
)

CREATE TABLE FACTURA(
    CODFAC      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ORDFAC      VARCHAR(50) NOT NULL,
    FECCREFAC   DATETIME NOT NULL,
    FECMODFAC   DATETIME NOT NULL,
    ESTFAC      INTEGER NOT NULL,
    IMPTOTFAC   DECIMAL(10,2) NOT NULL,
    ENVFAC      DECIMAL(10,2) NOT NULL,
    ENVDESFAC   DECIMAL(10,2) NOT NULL,
    HANDFAC     DECIMAL(10,2) NOT NULL,
    TOTFAC      DECIMAL(10,2) NOT NULL,
    DIRFAC      VARCHAR(500) NOT NULL,
    CODPOSFAC   VARCHAR(5) NOT NULL,
    PAIFAC      VARCHAR(45) NOT NULL,
    CIUFAC      VARCHAR(45) NOT NULL,
    DIVFAC      VARCHAR(45) NOT NULL,
    CODPER      INTEGER NOT NULL
)

CREATE TABLE GENERO(
    CODGEN      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DESGEN      VARCHAR(100) NOT NULL,
    FECCREGEN   DATETIME NOT NULL,
    FECMODGEN   DATETIME NOT NULL,
    ESTGEN      INTEGER NOT NULL
)

CREATE TABLE NACIONALIDAD(
    CODNAC      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DESNAC      VARCHAR(60) NOT NULL,
    ABRNAC      VARCHAR(4) NOT NULL,
    FECCRENAC   DATETIME NOT NULL,
    FECMODNAC   DATETIME NOT NULL,
    ESTNAC      INTEGER NOT NULL
)

CREATE TABLE PERSONA(
    CODPER      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NUMIDEPER   VARCHAR(12) NOT NULL,
    NOMPER      VARCHAR(100) NOT NULL,
    PRIAPEPER   VARCHAR(100) NOT NULL,
    SEGAPEPER   VARCHAR(45) NOT NULL,
    IMGPER      VARCHAR(100) NOT NULL,
    USERPER     VARCHAR(45) NOT NULL,
    PSWDPER     VARCHAR(45) NOT NULL,
    FECCREPER   DATETIME NOT NULL,
    FECMODPER   DATETIME NOT NULL,
    ESTPER      INTEGER NOT NULL,
    CODIDE      INTEGER NOT NULL,
    CODROL      INTEGER NOT NULL
)

CREATE TABLE ROL(
    CODROL      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMROL      VARCHAR(45) NOT NULL,
    FECCREROL   DATETIME NOT NULL,
    FECMODROL   DATETIME NOT NULL,
    ESTROL      INTEGER NOT NULL
)

CREATE TABLE SUBGENERO(
    CODSUBGEN       INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DESSUBGEN       VARCHAR(100) NOT NULL,
    FECCRESUBGEN    DATETIME NOT NULL,
    FECMODSUBGEN    DATETIME NOT NULL,
    ESTSUBGEN       INTEGER NOT NULL,
    CODGEN          INTEGER NOT NULL
)

CREATE TABLE TEMA(
    CODTEM      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    TITTEM      VARCHAR(200) NOT NULL,
    LETTEM      TEXT NOT NULL,
    FECCRETEM   DATETIME NOT NULL,
    FECMODTEM   DATETIME NOT NULL,
    ESTTEM      INTEGER NOT NULL,
    CODALB      INTEGER NOT NULL
)

CREATE TABLE IDENTIFICACION(
    CODIDE      INTEGER IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NOMIDE      VARCHAR(45) NOT NULL,
    FECCREIDE   DATETIME NOT NULL,
    FECMODIDE   DATETIME NOT NULL,
    ESTIDE      INTEGER NOT NULL
)

-- creación de las relaciones

/*Creando relaciones entre tablas (DISQUERA - ALBUM) */
ALTER TABLE ALBUM
    ADD CONSTRAINT DISQUERA_ALBUM FOREIGN KEY (CODDIS) REFERENCES DISQUERA(CODDIS)
GO

/*Creando relaciones entre tablas (ARTISTA - ALBUM) */
ALTER TABLE ALBUM
    ADD CONSTRAINT ARTISTA_ALBUM FOREIGN KEY (CODART) REFERENCES ARTISTA(CODART)
GO

/*Creando relaciones entre tablas (NACIONALIDAD - ARTISTA) */
ALTER TABLE ARTISTA
    ADD CONSTRAINT NACIONALIDAD_ARTISTA FOREIGN KEY (CODNAC) REFERENCES NACIONALIDAD(CODNAC)
GO

/*Creando relaciones entre tablas (SUBGENERO - ARTISTA) */
ALTER TABLE ARTISTA
    ADD CONSTRAINT SUBGENERO_ARTISTA FOREIGN KEY (CODSUBGEN) REFERENCES SUBGENERO(CODSUBGEN)
GO

/*Creando relaciones entre tablas (PERSONA - CARRITO) */
ALTER TABLE CARRITO
    ADD CONSTRAINT PERSONA_CARRITO FOREIGN KEY (CODPER) REFERENCES PERSONA(CODPER)
GO

/*Creando relaciones entre tablas (ALBUM - CARRITOALBUM) */
ALTER TABLE CARRITOALBUM
    ADD CONSTRAINT ALBUM_CARRITOALBUM FOREIGN KEY (CODALB) REFERENCES ALBUM(CODALB)
GO

/*Creando relaciones entre tablas (CARRITO - CARRITOALBUM) */
ALTER TABLE CARRITOALBUM
    ADD CONSTRAINT CARRITO_ALBUM FOREIGN KEY (CODCAR) REFERENCES CARRITO(CODCAR)
GO

/*Creando relaciones entre tablas (FACTURA - CARRITOALBUM) */
ALTER TABLE CARRITOALBUM
    ADD CONSTRAINT FACTURA_CARRITOALBUM FOREIGN KEY (CODFAC) REFERENCES FACTURA(CODFAC)
GO

/*Creando relaciones entre tablas (PERSONA - FACTURA) */
ALTER TABLE FACTURA
    ADD CONSTRAINT PERSONA_FACTURA FOREIGN KEY (CODPER) REFERENCES PERSONA(CODPER)
GO

/*Creando relaciones entre tablas (ROL - PERSONA) */
ALTER TABLE PERSONA
    ADD CONSTRAINT ROL_PERSONA FOREIGN KEY (CODROL) REFERENCES ROL(CODROL)
GO

/*Creando relaciones entre tablas (IDENTIFICACION - PERSONA) */
ALTER TABLE PERSONA
    ADD CONSTRAINT IDENTIFICACION_PERSONA FOREIGN KEY (CODIDE) REFERENCES IDENTIFICACION(CODIDE)
GO

/*Creando relaciones entre tablas (GENERO - SUBGENERO) */
ALTER TABLE SUBGENERO
    ADD CONSTRAINT GENERO_SUBGENERO FOREIGN KEY (CODGEN) REFERENCES GENERO(CODGEN)
GO

/*Creando relaciones entre tablas (ALBUM - TEMA) */
ALTER TABLE TEMA
    ADD CONSTRAINT ALBUM_TEMA FOREIGN KEY (CODALB) REFERENCES ALBUM(CODALB)
GO

SELECT * FROM DISQUERA
GO